### ISSUE TITLE
Make Search/Label Next panel wider or adjustable

### ISSUE THREAD

**Issue by keithcallenberg** [label-sleuth/label-sleuth#240]
**Is your feature request related to a problem?**
The sentences and paragraphs I am labeling are longer than those in the wiki_animals_2000 example dataset. Consequently, only a few elements are shown at a time in the right panel (when searching or using the Label Next feature). This also makes it frustrating to have to scroll down to the next element after every labeling action.

**What is the expected behavior?**
Since 90% of my time is spent in the right panel (searching or labeling next) the right panel should not only use 20% of the screen real estate. Ideally it would default to something more like 40% and/or be adjustable.

**Additional context (if any):**
Automatically scrolling down to the next element after labeling could also improve the UX.

**Comment by martinscooper** [comment]
Hi @keithcallenberg, thanks for creating this issue. This is a very good suggestion. 

Making the right panel wider definitely makes a lot of sense and that could be done easily. Making it adjustable would require some more work because the UI hasn't been built with that in mind, so it would require more work. However, I think it would be a really nice feature.

Could you clarify on "Automatically scrolling down to the next element after labeling could also improve the UX"?

**Comment by keithcallenberg** [comment]
> Could you clarify on "Automatically scrolling down to the next element after labeling could also improve the UX"?
After you click a label for your current element, most of the time you want to go to the next element in the list. Currently you must often scroll down manually to see that next element. Automatically scrolling down to the next element would place that element in view and minimize manual scrolling.

**Comment by martinscooper** [comment]
Closing this issue as it has been adressed. Right panel is now resizable. cc @keithcallenberg
